### ISSUE TITLE
Microsoft.Storage/storageAccount (2019-04-01)

### ISSUE THREAD

**Issue by alex-frankel** [Azure/arm-template-whatif#1]
### Describe the noise

**Resource type (i.e. Microsoft.Storage/storageAccounts)**
Microsoft.Storage/storageAccounts

**apiVersion (i.e. 2019-04-01)**
2019-04-01

**Client (PowerShell, Azure CLI, API)**
PowerShell

**Relevant ARM Template code (we only need the resource object specified in #1 and #2, but if it's easier you can include the entire template**
```json
    {
      "name": "[concat('storage', uniqueString(resourceGroup().id))]",
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2019-04-01",
      "sku": {
        "name": "Standard_LRS"
      },
      "kind": "Storage",
      "location":"[resourceGroup().location]"
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Clean diff

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/11078275/68731445-f73ccb80-0584-11ea-9b4b-894cf586aab3.png)

**Additional context**

**Comment by shenglol** [comment]
We have fixed the issue.

**Comment by alex-frankel** [comment]
Still seeing one noisy property:

![image](https://user-images.githubusercontent.com/11078275/77950097-e4e5d480-727c-11ea-9243-7ab7343254c0.png)

**Comment by alex-frankel** [comment]
But much better than before!

**Comment by shenglol** [comment]
Interesting...I checked the generated metadata and the API version is in it. Storage is doing put-as-patch so it should already be handled by the global put behavior rule. Let's give it a couple of more weeks and see if it goes away.

**Comment by shenglol** [comment]
I tested locally with the latest metadata and result is clean. It turns out the final fix for storage account was not included in ARM w11 deployment train...we'll have to wait for w15.

**Comment by alex-frankel** [comment]
Awesome!

**Comment by alex-frankel** [comment]
fixed in latest deployed noise reduction
