### ISSUE TITLE
Microsoft.Network/virtualNetworks properties.virtualNetworkPeerings shown as Delete

### ISSUE THREAD

**Issue by shenglol** [Azure/arm-template-whatif#163]
## Describe the noise

**Resource type** (i.e. Microsoft.Network/virtualNetworks)

**apiVersion** (i.e. 2019-09-01)

**Client (PowerShell, Azure CLI, or API)**

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```
{
  "type": "Microsoft.Network/virtualNetworks",
  "apiVersion": "2019-09-01",
  "name": "myVNet",
  "location": "eastus",
  "properties": {
    // There are existing virtualNetworkPeerings in the resource group, but they are not declared in properties
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes.
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```JSON
{
  "resourceId": "/subscriptions/00000000-0000-0000​-0000-000000000000/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myVNet",
  "changeType": "Modify",
  "delta": [
    {
      "path": "properties.virtualnetworkpeerings",
      "propertyChangeType": "Delete",
      "before": [
          {
              ...
          }
        ]
    }
  ]
}
```

**Additional context**

**Comment by shenglol** [comment]
[w11].

**Comment by shenglol** [comment]
Fix is deployed.

**Comment by gavhooper** [comment]
@shenglol This is still an issue using version 4.3.1 of Az.Resources PowerShell Module. No peerings are specified in the ARM template, just a vnet like the below. But still `Get-AzResourceGroupDeploymentWhatIfResult` states it is going to delete the peerings.

`        {
            "type": "Microsoft.Network/virtualNetworks",
            "apiVersion": "2021-02-01",
            "name": "[parameters('virtualNetworks_vnet_name')]",
            "location": "westeurope",
            "properties": {
                "addressSpace": {
                    "addressPrefixes": "[parameters('env').addressPrefixes]"
                },
                "subnets": [
                    {
                        "name": "subnet1",
                        "properties": {
                            "addressPrefix": "[parameters('env').subnet1]",
                            "delegations": [],
                            "privateEndpointNetworkPolicies": "Enabled",
                            "privateLinkServiceNetworkPolicies": "Enabled"
                        }
                    }
                ],
                "enableDdosProtection": false
            }
        }`
        
        
` Get-AzResourceGroupDeploymentWhatIfResult`

        ` ~ Microsoft.Network/virtualNetworks/vnet-dev [2021-02-01]
    - properties.virtualNetworkPeerings: [
        0:

          name:                                         "peer"
          properties.allowForwardedTraffic:             true
          properties.allowGatewayTransit:               false
          properties.allowVirtualNetworkAccess:         true
          properties.doNotVerifyRemoteGateways:         false
          properties.peeringSyncLevel:                  "FullyInSync"
          properties.remoteAddressSpace.addressPrefixes: [
            0: "10.2.0.0/16"
          ]
          properties.remoteVirtualNetwork.id:           "/subscriptions/67768/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet-test"
          properties.remoteVirtualNetworkAddressSpace.addressPrefixes: [
            0: "10.2.0.0/16"
          ]
          properties.useRemoteGateways:                 false

      ]

Resource changes: 1 to modify.`
